name: FlyingBounties
version: '1.0.3'
main: me.muszek_.playerBounty.PlayerBounty
api-version: '1.20'
depend:
  - Vault
commands:
  flyingBounties:
    description: '&ePlace bounty on players'
    aliases:
      - bounty
      - playerbounty
    usage: |-
      /bounty <arg>
