name: 777-Zlecenia
version: '1.0.1'
main: me.muszek_.playerBounty.PlayerBounty
api-version: '1.20'
depend:
  - Vault
commands:
  playerbounty:
    description: '&ePlace bounty on players'
    aliases:
      - bounty
      - zlecenia
    usage: |-
      /bounty <arg>
