name: FlyingBounties
version: '${project.version}'
main: me.muszek_.playerBounty.PlayerBounty
depend:
  - Vault
commands:
  playerbounty:
    description: '&ePlace bounty on players'
    aliases:
      - bounty
      - fb
      - flyingbounties
    usage: |-
      /bounty <arg>
